import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import logo from "../../public/assets/logo/logo.png";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Fiqor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
          </div>
        </div>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src={logo}
            alt="Fiqor Logo"
            width={600}
            height={300}
            priority
          />
        </div>
        <div className={styles.grid}>
        </div>
      </main>
    </>
  )
}
